### ISSUE TITLE
Add About Us Page

### ISSUE THREAD

**Issue by imhardikdesai** [imhardikdesai/Currency-Converter#1]
### Description

Add About Us Page

### Scope

- Add About us Page with Proper Styling of Chakra UI, use ready components from here 
- https://chakra-templates.dev/

### Acceptance Criteria

- You can also Create an Separate issue for any Changes
- All scope are fix correctly, if you have made proper PR and changes then your PR merge by `hacktoberfest` and `hacktoberfest-accepted` label

### Labels

- Page Addition
- Hacktoberfest

**Comment by mukulpythondev** [comment]
I am interested to work on this please assign to me

**Comment by imhardikdesai** [comment]
@mukulpythondev Sure i will assign this to you
