### ISSUE TITLE
copyright year in footer not updated

### ISSUE THREAD

**Issue by rhnas110** [imhardikdesai/Currency-Converter#15]
Hi Sir @imhardikdesai 
### Issue Description:
Currently I saw the code in the footer of the website for the copyright year is still static and not updated, I want to add a dynamic year copyright in the footer of the website.

### Screenshots:
![image](https://github.com/imhardikdesai/Currency-Converter/assets/51848196/52716489-7e30-4245-a6a5-5dfe5232aad3)

### Additional information
Can you take my advice and assign this task to me Sir @imhardikdesai ? and I am new to open source contributions and I would love to contribute to your project! I also participated in Hacktoberfest2023.

**Comment by imhardikdesai** [comment]
@rhnas110 please start working on it
