### ISSUE TITLE
Add Contact Us Page

### ISSUE THREAD

**Issue by imhardikdesai** [imhardikdesai/Currency-Converter#2]
### Description

Add Contact Us Page

### Scope

- Add Contact us Page with Proper Styling of Chakra UI, use ready components from here 
- https://chakra-templates.dev/

### Acceptance Criteria

- You can also Create an Separate issue for any Changes
- All scope are fix correctly, if you have made proper PR and changes then your PR merge by `hacktoberfest` and `hacktoberfest-accepted` label

### Labels

- Page Addition
- Hacktoberfest

**Comment by Kinshu-Learner** [comment]
I would like to work on this issue, please assign me :D

**Comment by imhardikdesai** [comment]
> I would like to work on this issue, please assign me :D

Sure, Start working on it

**Comment by Kinshu-Learner** [comment]
> > I would like to work on this issue, please assign me :D
> 
> Sure, Start working on it

Could you please check my PR once and give any feedbacks if necessary?

**Comment by imhardikdesai** [comment]
> > > I would like to work on this issue, please assign me :D
> > 
> > 
> > Sure, Start working on it
> 
> Could you please check my PR once and give any feedbacks if necessary?

Looks Good, can you just fix this following warning so it will deploy successfully
- https://app.netlify.com/sites/currency-converter-live-app/deploys/651bdf63114d6f00087be752
#4
