### ISSUE TITLE
Netlify About/Contact Page reload show error

### ISSUE THREAD

**Issue by thesohailjafri** [imhardikdesai/Currency-Converter#7]
Hii @imhardikdesai 

I have noticed while experimenting with your project [domain](https://currency-converter-live-app.netlify.app/) that on the about/contact page reload it shows a generic netlify error rather than the page itself

![image](https://github.com/imhardikdesai/Currency-Converter/assets/66732877/6d162bd6-653e-4a2e-b97a-9cfb36a66a1c)

I have faced this problem with netlify before and I would like to contribute to your project to fix this issue

So please allow me to contribute by assigning this issue to me and It would be great if you mark this issue as **hacktoberfest** and **hacktoberfest-accepted**

[StackOverflow Problem Refrence](https://stackoverflow.com/questions/58065603/netlify-renders-404-on-page-refresh-using-react-and-react-router)

**Comment by imhardikdesai** [comment]
Thank you for referring issue @thesohailjafri please start working on it

**Comment by thesohailjafri** [comment]
On it

**Comment by thesohailjafri** [comment]
Hii @imhardikdesai I have fixed this issue 

Please verify the fix on 👉 https://deploy-preview-8--currency-converter-live-app.netlify.app/About 

Now page will load without any error⚡
